framework:
    test: ~
    session:
        #storage_id: session.storage.mock_file
        storage_id: session.storage.filesystem
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
        main:
            http_basic: ~

doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     '%kernel.cache_dir%/test.db'

liip_functional_test:
    cache_sqlite_db: true
