
opifer_cms_dashboard:
    path: /
    defaults: { _controller: OpiferCmsBundle:Backend/Dashboard:view }

opifer_cms_menu_index:
    path: /menu
    defaults: { _controller: OpiferCmsBundle:Backend/Menu:index }
    methods: [GET]

opifer_cms_menu_create:
    path: /menu/create/{type}
    defaults: { _controller: OpiferCmsBundle:Backend/Menu:create }
    methods: [GET, POST]
    requirements:
        type: group|item

opifer_cms_menu_edit:
    path: /menu/edit/{id}
    defaults: { _controller: OpiferCmsBundle:Backend/Menu:edit }
    methods: [GET, POST]
    requirements:
        id: \d+

opifer_cms_menu_delete:
    path: /menu/delete/{id}
    defaults: { _controller: OpiferCmsBundle:Backend/Menu:delete }
    methods: [GET]
    requirements:
        id: \d+

opifer_cms_setting_index:
    path: /settings
    defaults: { _controller: OpiferCmsBundle:Backend/Setting:index }

opifer_cms_template_index:
    path: /templates
    defaults: { _controller: OpiferCmsBundle:Backend/Template:index }

opifer_cms_template_create:
    path: /templates/create
    defaults: { _controller: OpiferCmsBundle:Backend/Template:create }

opifer_cms_template_edit:
    path: /templates/edit/{id}
    defaults: { _controller: OpiferCmsBundle:Backend/Template:edit }
    requirements:
        id: \d+

opifer_cms_template_delete:
    path: /templates/delete/{id}
    defaults: { _controller: OpiferCmsBundle:Backend/Template:delete }
    requirements:
        id: \d+

opifer_cms_layout_index:
    path: /layouts
    defaults: { _controller: OpiferCmsBundle:Backend/Layout:index }

opifer_cms_layout_create:
    path: /layouts/create
    defaults: { _controller: OpiferCmsBundle:Backend/Layout:create }

opifer_cms_layout_edit:
    path: /layouts/edit/{id}
    defaults: { _controller: OpiferCmsBundle:Backend/Layout:edit }
    requirements:
        id: \d+

opifer_cms_layout_delete:
    path: /layouts/delete/{id}
    defaults: { _controller: OpiferCmsBundle:Backend/Layout:delete }
    requirements:
        id: \d+

opifer_cms_cronjob_index:
    path: /cronjobs
    defaults: { _controller: OpiferCmsBundle:Backend/Cronjob:index }

opifer_cms_cronjob_create:
    path: /cronjobs/create
    defaults: { _controller: OpiferCmsBundle:Backend/Cronjob:create }

opifer_cms_cronjob_edit:
    path: /cronjobs/edit/{id}
    defaults: { _controller: OpiferCmsBundle:Backend/Cronjob:edit }
    requirements:
        id: \d+

opifer_cms_cronjob_delete:
    path: /cronjobs/delete/{id}
    defaults: { _controller: OpiferCmsBundle:Backend/Cronjob:delete }
    requirements:
        id: \d+

opifer_cms_user_index:
    path: /users
    defaults: { _controller: OpiferCmsBundle:Backend/User:index }

opifer_cms_user_new:
    path: /users/new
    defaults: { _controller: OpiferCmsBundle:Backend/User:new }

opifer_cms_user_edit:
    path: /users/edit/{id}
    defaults: { _controller: OpiferCmsBundle:Backend/User:edit }
    requirements:
        id: \d+

opifer_ckeditor_content:
    path: /ckeditor/content
    defaults: { _controller: OpiferCmsBundle:CKEditor:content }
    options:
        expose: true

opifer_ckeditor_media:
    path: /ckeditor/media
    defaults: { _controller: OpiferCmsBundle:CKEditor:media }
    options:
        expose: true

opifer_redirect_admin:
    resource: "@OpiferRedirectBundle/Resources/config/routing.yml"
    prefix:   /redirect

opifer_form_admin:
    resource: "@OpiferFormBundle/Resources/config/routing_admin.yml"

opifer_eav_admin:
    resource: "@OpiferEavBundle/Resources/config/routing.yml"

opifer_content_admin:
    resource: "@OpiferContentBundle/Resources/config/routing.yml"

opifer_media_admin:
    resource: "@OpiferMediaBundle/Resources/config/routing.yml"

# Users
fos_user_security_login:
    pattern:  /login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix:   /group
